export interface OceanSettings {
  resolution: string
  stylized: boolean
  animationPaused: boolean
  animationSpeed: number
  timeOffset: number
  envIntensity: number
  lightIntensity: number
  shadows: boolean
  glow: boolean
  zqsd: boolean
  debug: boolean

  inclination: number
  azimuth: number
  luminance: number
  turbidity: number
  rayleigh: number
  mie: number
  mieG: number
  fogMode: string
  fogColor: string
  fogStart: number
  fogEnd: number
  fogDensity: number
  exposure: number
  contrast: number

  gravity: number
  depth: number
  lambda: number
  localScale: number
  windSpeed: number
  windDirection: number
  localFetch: number
  spread: number
  swellMix: number
  peak: number
  shortFade: number
  swellScale: number
  swellWind: number
  swellDirection: number
  swellFetch: number
  swellSpread: number
  swellAmount: number
  swellPeak: number
  swellFade: number

  largeLength: number
  mediumLength: number
  smallLength: number
  largeVertical: number
  mediumVertical: number
  smallVertical: number
  largeHorizontal: number
  mediumHorizontal: number
  smallHorizontal: number
  largeNormal: number
  mediumNormal: number
  smallNormal: number
  largeFoam: number
  mediumFoam: number
  smallFoam: number

  seaLevel: number
  /**
   * 海面网格每边的细分段数（顶点数 = (值 + 1)²，面片数 = 值²）。
   * 海面平面固定为 700 × 700 米，因此单个面片边长 = 700 ÷ 该值。
   */
  facetResolution: number
  /**
   * 面片顶点在水平方向的抖动幅度（单位为格宽的比例）。
   * 0 = 规则格纹；0.3 ~ 0.4 得到参考图那种不规则碎面。过大时四边形会被压扁。
   */
  facetJitter: number
  lengthScale: number
  vertexDensity: number
  clipLevels: number
  skirtSize: number
  waveFadeStart: number
  waveFadeEnd: number
  facetFadeStart: number
  facetFadeEnd: number
  normalFadeStart: number
  normalFadeEnd: number
  followCamera: boolean
  wireframe: boolean
  noLod: boolean

  waterColor: string
  valleyColor: string
  slopeColor: string
  crestColor: string
  shallowColor: string
  deepColor: string
  facetStrength: number
  detailNormalStrength: number
  normalScaleX: number
  normalScaleZ: number
  shadingContrast: number
  shadingBias: number
  toneSteps: number
  toneTransition: number
  colorPatches: boolean
  patchScale: number
  patchStrength: number
  patchSpeedX: number
  patchSpeedZ: number
  heightColorStrength: number
  heightColorBias: number
  slopeColorStrength: number
  slopeColorBias: number
  lightColorStrength: number
  shallowStart: number
  shallowEnd: number
  saturation: number
  brightness: number
  sssColor: string
  sssStrength: number
  sssBase: number
  sssScale: number

  maxGloss: number
  roughness: number
  lodScale: number
  fresnelStrength: number
  fresnelBias: number
  highlightColor: string
  highlightStrength: number
  highlightSharpness: number
  glintScale: number
  glintAspect: number
  glintAngle: number
  glintThreshold: number
  glintDistortion: number

  crestFoam: boolean
  contactFoam: boolean
  foamColor: string
  foam: number
  foamContact: number
  foamBiasLarge: number
  foamBiasMedium: number
  foamBiasSmall: number
  foamHeightWeight: number
  foamSlopeWeight: number
  foamEdgeSoftness: number
  foamMaskScale: number
  foamMaskAspect: number
  foamMaskAngle: number
  foamFoldBias: number
  foamBreakup: number
  foamDistortion: number
  foamSpeedX: number
  foamSpeedZ: number
  foamDecay: number
  foamFadeStart: number
  foamFadeEnd: number

  buoyancy: boolean
  damping: number
  steps: number
  buoyOffset: number
  heaveScale: number
  rollScale: number
  pitchScale: number

  cameraX: number
  cameraY: number
  cameraZ: number
  cameraPitch: number
  cameraYaw: number
  cameraSpeed: number
  cameraFov: number

  wakeEnabled: boolean
  wakeInitialWidth: number
  wakeSpreadSpeed: number
  wakeAngle: number
  wakeWaterOffset: number
  wakeWidthResponse: number
  wakeLengthResponse: number
  wakeFoamResponse: number
  wakeColor: string
  wakeWaterColor: string
  wakeBrightness: number
  wakeBreakup: number
  wakeTextureScale: number
  wakeLifetime: number
  wakeSampleDistance: number
  wakeMaxPoints: number
  sprayEnabled: boolean
  sprayRate: number
  sprayLifetime: number
  spraySize: number
  sprayVelocityX: number
  sprayVelocityY: number
  sprayVelocityZ: number
  sprayGravityX: number
  sprayGravityY: number
  sprayGravityZ: number
  sprayColor: string
}

export const defaultOceanSettings: Readonly<OceanSettings> = {
  resolution: '256',
  stylized: true,
  animationPaused: false,
  animationSpeed: 1,
  timeOffset: 0,
  envIntensity: 1,
  lightIntensity: 1,
  shadows: true,
  glow: false,
  zqsd: false,
  debug: false,
  inclination: 0.25,
  azimuth: -0.3,
  luminance: 1,
  turbidity: 10,
  rayleigh: 2,
  mie: 0.005,
  mieG: 0.8,
  fogMode: 'linear',
  fogColor: '#8ba8bc',
  fogStart: 130,
  fogEnd: 640,
  fogDensity: 0.002,
  exposure: 1,
  contrast: 1,
  gravity: 9.81,
  depth: 3,
  lambda: 1,
  localScale: 0.72,
  windSpeed: 1.65,
  windDirection: -28,
  localFetch: 100000,
  spread: 1,
  swellMix: 0.198,
  peak: 3.3,
  shortFade: 0.01,
  swellScale: 0.72,
  swellWind: 1.1,
  swellDirection: 14,
  swellFetch: 300000,
  swellSpread: 1,
  swellAmount: 1,
  swellPeak: 3.3,
  swellFade: 0.01,
  largeLength: 34,
  mediumLength: 14,
  smallLength: 5.5,
  largeVertical: 1,
  mediumVertical: 0.82,
  smallVertical: 0.42,
  largeHorizontal: 0.58,
  mediumHorizontal: 0.4,
  smallHorizontal: 0.22,
  largeNormal: 1,
  mediumNormal: 0.85,
  smallNormal: 0.35,
  largeFoam: 1,
  mediumFoam: 1,
  smallFoam: 0.5,
  seaLevel: 0,
  facetResolution: 190,
  facetJitter: 0.34,
  lengthScale: 15,
  vertexDensity: 30,
  clipLevels: 8,
  skirtSize: 10,
  waveFadeStart: 900,
  waveFadeEnd: 2200,
  facetFadeStart: 140,
  facetFadeEnd: 700,
  normalFadeStart: 220,
  normalFadeEnd: 1000,
  followCamera: true,
  wireframe: false,
  noLod: true,
  waterColor: '#12638c',
  valleyColor: '#0a5c80',
  slopeColor: '#1c7398',
  crestColor: '#2b93b4',
  shallowColor: '#57c7c2',
  deepColor: '#032d4b',
  facetStrength: 0.7,
  detailNormalStrength: 1,
  normalScaleX: 1,
  normalScaleZ: 1,
  shadingContrast: 1.05,
  shadingBias: 0.12,
  toneSteps: 4,
  toneTransition: 0,
  colorPatches: true,
  patchScale: 11,
  patchStrength: 0.09,
  patchSpeedX: 0.03,
  patchSpeedZ: -0.015,
  heightColorStrength: 0.65,
  heightColorBias: 0.48,
  slopeColorStrength: 1.2,
  slopeColorBias: -0.1,
  lightColorStrength: 0.18,
  shallowStart: 0,
  shallowEnd: 18,
  saturation: 1.08,
  brightness: 1.1,
  sssColor: '#6df1fe',
  sssStrength: 0.15,
  sssBase: -0.26,
  sssScale: 4.7,
  maxGloss: 0.91,
  roughness: 0.18,
  lodScale: 7.12,
  fresnelStrength: 1,
  fresnelBias: 0,
  highlightColor: '#ffe6ba',
  highlightStrength: 0.7,
  highlightSharpness: 46,
  glintScale: 0.4,
  glintAspect: 4,
  glintAngle: 18,
  glintThreshold: 0.44,
  glintDistortion: 0.22,
  crestFoam: true,
  contactFoam: true,
  foamColor: '#f5e8d4',
  foam: 1.2,
  foamContact: 1,
  foamBiasLarge: 0.44,
  foamBiasMedium: 0.54,
  foamBiasSmall: 0.72,
  foamHeightWeight: 0.04,
  foamSlopeWeight: 0.08,
  foamEdgeSoftness: 0.09,
  foamMaskScale: 0.22,
  foamMaskAspect: 2.4,
  foamMaskAngle: -30,
  foamFoldBias: 0.9,
  foamBreakup: 0.35,
  foamDistortion: 0.2,
  foamSpeedX: 0.2,
  foamSpeedZ: 0.1,
  foamDecay: 0.5,
  foamFadeStart: 260,
  foamFadeEnd: 580,
  buoyancy: true,
  damping: 0.2,
  steps: 3,
  buoyOffset: 0,
  heaveScale: 1,
  rollScale: 1,
  pitchScale: 1,
  cameraX: 0,
  cameraY: 14,
  cameraZ: -42,
  cameraPitch: -7,
  cameraYaw: 180,
  cameraSpeed: 2,
  cameraFov: 50,
  wakeEnabled: true,
  wakeInitialWidth: 1.35,
  wakeSpreadSpeed: 0.82,
  wakeAngle: 20,
  wakeWaterOffset: 0.18,
  wakeWidthResponse: 1,
  wakeLengthResponse: 1,
  wakeFoamResponse: 1,
  wakeColor: '#eefcff',
  wakeWaterColor: '#4bb7ca',
  wakeBrightness: 1.0,
  wakeBreakup: 0.55,
  wakeTextureScale: 0.32,
  wakeLifetime: 9,
  wakeSampleDistance: 0.4,
  wakeMaxPoints: 128,
  sprayEnabled: true,
  sprayRate: 6,
  sprayLifetime: 1.2,
  spraySize: 0.18,
  sprayVelocityX: 0,
  sprayVelocityY: 0.8,
  sprayVelocityZ: -0.4,
  sprayGravityX: 0,
  sprayGravityY: -1.6,
  sprayGravityZ: 0,
  sprayColor: '#fff4de',
}
